# 키바나 설정파일
server.name: kibana
server.host: "0.0.0.0"  # 모든 네트워크 인터페이스에서 수신하도록 설정

# Elasticsearch 서버 정보
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: "elastic"
elasticsearch.password: "elastic123!@#"
