name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: application.yml 파일 만들기
        run: |
          mkdir -p ./src/main/resources/config
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/config/application.yml

      - name: application.properties 파일 만들기
        run: |
          mkdir -p ./src/main/resources/config
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/config/application.properties

      - name: application-test.yml 파일 만들기
        run: |
          mkdir -p ./src/test/resources/config
          echo "${{ secrets.APPLICATION_TEST_YML }}" > ./src/test/resources/config/application-test.yml

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build
